### PR TITLE
R2023 09

### PR DESCRIPTION
**Pull request by nielsson4711**
R2023-09 runs. ID upload will be added soon.

### CODE REVIEW

**Review by datenreisen — APPROVED** [review]

**Review by rettichschnidi — CHANGES_REQUESTED** [review]
I can not really say anything about the content, but before I can merge this, please resolve the conflicts.

**Comment by nielsson4711** [comment]
> I can not really say anything about the content, but before I can merge this, please resolve the conflicts.
conflicts resolved (App.svelte re. print layout)

**Review by rettichschnidi — CHANGES_REQUESTED** [review]
1. When I build this, I get security warnings:

    ```shell
    $ npm install
    npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
    npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
    
    added 211 packages, and audited 212 packages in 6s
    
    26 packages are looking for funding
      run `npm fund` for details
    
    3 vulnerabilities (1 moderate, 2 high)
    
    To address all issues, run:
      npm audit fix
    
    Run `npm audit` for details.
    ```

    I think those should be resolved before merging.

2. A letter generated with the old version can no longer be used to generate a new letter. It seems like the steps got renamed.
   - Old URL: https://wwwtest.digitale-gesellschaft.ch/auskunftsbegehren.003/#%7B%22v%22:1,%22org%22:%22Agrisano%22,%22entry%22:%22org%22,%22types%22:%5B%5D,%22name%22:%22Max%20Muster%22,%22address%22:%22Musterstrasse%201%5Cn1234%20Musterdorf%22,%22step%22:%22letter%22,%22date%22:%2229.8.2023%22%7D (note the step="letter")
   - New URL: https://wwwtest.digitale-gesellschaft.ch/auskunftsbegehren/#%7B%22v%22:1,%22org%22:%22Agrisano%22,%22entry%22:%22org%22,%22types%22:%5B%5D,%22name%22:%22Max%20Muster%22,%22address%22:%22Musterstrasse%201%5Cn1234%20Musterdorf%22,%22step%22:%22print%22,%22date%22:%2229.8.2023%22%7D (note the step="print")

    Is this intended? Would it make sense to address this somehow. Maybe make it work or tell the user that old data can no longer be used due to the new law?

In order to not block testing, I built [the current state of this PR](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren/actions/runs/6006677749), 0bb770700a84cd0211cca8ea1f5183101e6d0edc, combined it with the current state [from Datenauskunftsbegehren-Data](https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data/commit/5ef5c8c1603e536d10be5313a3236476f1189a43) and uploaded it to https://wwwtest.digitale-gesellschaft.ch/auskunftsbegehren for testing.

**Comment by nielsson4711** [comment]
## re 1: security warnings
disclaimer: I'm not experienced in contemporary javascript / npm.

### local diagnosis

There is no "direct" dependency for those libraries within package.json (see "grep" output below). It seems the dependencies were brought in indirectly by another component. Checking for updates and/or vulnerabilities within my dev env, the build system doesn't show up with warnings (see "npm" output below).

Thus I've no clue what and where to fix.

**Versions & warnings**
```
% npm --version
9.6.6
% npm update  

added 6 packages, removed 5 packages, changed 40 packages, and audited 214 packages in 33s

28 packages are looking for funding
  run `npm fund` for details


**Dependencies**
```
% grep -i -e "stable" -e "cssnano"  package.json package-lock.json
package-lock.json:    "node_modules/@types/cssnano": {
package-lock.json:      "resolved": "https://registry.npmjs.org/@types/cssnano/-/cssnano-5.1.0.tgz",
package-lock.json:      "deprecated": "This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.",
package-lock.json:        "cssnano": "*"
package-lock.json:    "node_modules/cssnano": {
package-lock.json:      "resolved": "https://registry.npmjs.org/cssnano/-/cssnano-5.1.12.tgz",
package-lock.json:        "cssnano-preset-default": "^5.2.12",
package-lock.json:        "url": "https://opencollective.com/cssnano"
package-lock.json:    "node_modules/cssnano-preset-default": {
package-lock.json:      "resolved": "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-5.2.12.tgz",
package-lock.json:        "cssnano-utils": "^3.1.0",
package-lock.json:    "node_modules/cssnano-utils": {
package-lock.json:      "resolved": "https://registry.npmjs.org/cssnano-utils/-/cssnano-utils-3.1.0.tgz",
package-lock.json:        "cssnano-utils": "^3.1.0",
package-lock.json:        "cssnano-utils": "^3.1.0",
package-lock.json:        "cssnano-utils": "^3.1.0",
package-lock.json:        "cssnano-utils": "^3.1.0",
package-lock.json:        "@types/cssnano": "^5.0.0",
package-lock.json:        "cssnano": "^5.0.15",
package-lock.json:    "node_modules/stable": {
package-lock.json:      "resolved": "https://registry.npmjs.org/stable/-/stable-0.1.8.tgz",
package-lock.json:      "deprecated": "Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility",
package-lock.json:        "stable": "^0.1.8"

```

## re 2: seamless reuse of saved data from previous version ("stored urls")
Opening: 
The feature "migration" wasn't requested at all.

The application got extended from one letter (internally named 'letter') towards 5 letters, with 2 directly depending on the first, and 3 depending on the answers to the first. Each letters data lifecycle follows the steps "entry & selected data", "display & edit" and "output". The internal naming of letters was changed to maintain readability. Thus, the aim "write a letter" became 'data_info_request' and got the siblings {unanswered, incomplete_answer, data_correction, data_deletion}.

Idem.
A way out can be to enable for processing of 'letter' in parallel to 'data_info_request'.
.. a matter of time ..

**Review by rettichschnidi — COMMENTED** [review]
1. Same here, I have no idea about Javascript/npm ecosystem. :)
2. Sounds like quite some extra work.

For this reason, I think we should just merge as is.

What's the reason why you deleted the source branch?

**Pull request closed without merging**
